# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  recurring_charge_name: Test Recurring Charge
  recurring_charge_price: 10
  recurring_charge_terms: This is important terms
  recurring_charge_trial_days: 7
  is_test_charge: true
# Environmental secrets are only available for that specific environment.

development:
  host: https://c72a0e96.ngrok.io
  secret_key_base: 6f65171711e1c4f338949717e1aac2754339d00625062064962f8df200488f84e9d50bf0a2868bf1c5f3ee20c86cadfc7e3f537f0b90b10538f71d85ae824b08

test:
  secret_key_base: 2e72ab1deb26f130d52c3cd76cbec44e35fc66be724aa6a1881b82ca89e603ee415217745f2557f5c281ec5259ccf86ef4efe0d2d0aaf94b0c619a782465bfb9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
